name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      #
      - name: install
        run: npm install
    
      #
      - name: test
        run: npm test
      
      # failure
      - name: The job has failed
        if: ${{ failure() }}